npmScopes:
  inductiveautomation:
    npmRegistryServer: "https://nexus.inductiveautomation.com/repository/node-packages/"
  inductiveautomation-beta:
    npmRegistryServer: "https://nexus.inductiveautomation.com/repository/inductiveautomation-beta-node-packages/"