Network=Network
Hostname.Name=Hostname
Hostname.Desc=Hostname/IP address of the SNMP device.
Port.Name=Port
Port.Desc=Port to connect to on the remote device.
CommunityRead.Name=Read Community
CommunityRead.Desc=The SNMP community string used for reads.
CommunityWrite.Name=Write Community
CommunityWrite.Desc=The SNMP community string used for writes.
Healthcheck=Healthcheck
HealthcheckFrequency.Name=Healthcheck Frequency
HealthcheckFrequency.Desc=The time in milliseconds between connection validation checks.
HealthcheckOid.Name=Healthcheck OID
HealthcheckOid.Desc=This OID will be queried to validate the connection.