Connectivity=Connectivity
Hostname.Name=Hostname
Hostname.Desc=Hostname/IP address of the remote device.
Port.Name=Port
Port.Desc=Port to connect to on the remote device.
Timeout.Name=Timeout
Timeout.Desc=Maximum amount of time to wait for a response in milliseconds.
Community=Community
CommunityRead.Name=Read Community
CommunityRead.Desc=The SNMP community used for reads.
CommunityWrite.Name=Write Community
CommunityWrite.Desc=The SNMP community used for writes. If empty, writing to the device will be disabled.
Healthcheck=Healthcheck
HealthcheckFrequency.Name=Healthcheck Frequency
HealthcheckFrequency.Desc=The time in milliseconds between connection validation checks. If zero or negative, health checks will not be performed.
HealthcheckOid.Name=Healthcheck OID
HealthcheckOid.Desc=This OID will be queried to validate the connection. If empty, health checks will not be performed.