Connectivity=Connectivity
Address.Name=Address
Address.Desc=<br>The format of the SNMP connect URL is:<br><code><b>type</b>:<b>address</b></code><br>With the two parameters (in bold)<ul style=list-style-type:none;margin-left:10px><li><b>type</b>: The transport protocol used for SNMP communication. Allowed values include <code>udp</code>, <code>tcp</code>, <code>tls</code>, <code>dtls</code>, and <code>unix</code>.<li><b>address</b>: The type-specific target network address, which typically includes the host name or IP address and an optional port number. For <code>udp</code> and <code>tcp</code> connection types, the address is of the form <code><b>hostname</b>/<b>port</b></code>.</ul><p>Example: <code>udp:127.0.0.1/161</code>
Port.Name=Port
Port.Desc=Port to connect to on the remote device.
Timeout.Name=Timeout
Timeout.Desc=Maximum amount of time to wait for a response in milliseconds.
Community=Community
CommunityRead.Name=Read Community
CommunityRead.Desc=The SNMP community used for reads.
CommunityWrite.Name=Write Community
CommunityWrite.Desc=The SNMP community used for writes. If empty, writing to the device will be disabled.
Healthcheck=Healthcheck
HealthcheckFrequency.Name=Healthcheck Frequency
HealthcheckFrequency.Desc=The time in milliseconds between connection validation checks. If zero or negative, health checks will not be performed.
HealthcheckOid.Name=Healthcheck OID
HealthcheckOid.Desc=This OID will be queried to validate the connection. If empty, health checks will not be performed.