[versions]
ia-gson = "2.10.1"
if97 = "2.0.0"
ignition-module = "0.5.0"
ignition-sdk = "8.1.33"
java = "21"
jetty = "10.0.21"
kotlin = "2.1.21"
kotest = "6.0.0"
node-gradle = "7.1.0"
snmp4j = "3.9.3"
spotless = "8.0.0"

[plugins]
ignition-module = { id = "io.ia.sdk.modl", version.ref = "ignition-module" }
kotest = { id = "io.kotest", version.ref = "kotest"}
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
node-gradle = { id = "com.github.node-gradle.node", version.ref = "node-gradle" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
if97 = { group = "com.hummeling", name = "if97", version.ref = "if97"}
ignition-common = { group = "com.inductiveautomation.ignitionsdk", name = "ignition-common", version.ref = "ignition-sdk" }
ignition-gson = { group = "com.inductiveautomation.ignition", name = "ia-gson", version.ref = "ia-gson"}
ignition-client-api = { group = "com.inductiveautomation.ignitionsdk", name = "client-api", version.ref = "ignition-sdk" }
ignition-designer-api = { group = "com.inductiveautomation.ignitionsdk", name = "designer-api", version.ref = "ignition-sdk" }
ignition-driver-api = { group = "com.inductiveautomation.ignitionsdk", name = "driver-api", version.ref = "ignition-sdk" }
ignition-gateway-api = { group = "com.inductiveautomation.ignitionsdk", name = "gateway-api", version.ref = "ignition-sdk" }
ignition-vision-client-api = { group = "com.inductiveautomation.ignitionsdk", name = "vision-client-api", version.ref = "ignition-sdk" }
ignition-perspective-common = { group = "com.inductiveautomation.ignitionsdk", name = "perspective-common", version.ref = "ignition-sdk" }
ignition-perspective-designer = { group = "com.inductiveautomation.ignitionsdk", name = "perspective-designer", version.ref = "ignition-sdk" }
ignition-perspective-gateway = { group = "com.inductiveautomation.ignitionsdk", name = "perspective-gateway", version.ref = "ignition-sdk" }
jetty-server = { group = "org.eclipse.jetty", name = "jetty-server", version.ref = "jetty" }
jetty-servlet = { group = "org.eclipse.jetty", name = "jetty-servlet", version.ref = "jetty" }
jetty-servlets = { group = "org.eclipse.jetty", name = "jetty-servlets", version.ref = "jetty" }
snmp4j = { group = "org.snmp4j", name = "snmp4j", version.ref = "snmp4j"}

# test framework
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-junit = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-property = { group = "io.kotest", name = "kotest-property", version.ref = "kotest" }
kotest-data = { group = "io.kotest", name = "kotest-framework-datatest", version.ref = "kotest" }

[bundles]
common = [
    "ignition-gson",
    "ignition-common"
]
gateway = [
    "ignition-gson",
    "ignition-common",
    "ignition-driver-api",
    "ignition-gateway-api",
]
designer = [
    "ignition-gson",
    "ignition-common",
    "ignition-designer-api",
]
client = [
    "ignition-common",
    "ignition-client-api",
    "ignition-vision-client-api",
]
perspectiveCommon = [
    "ignition-gson",
    "ignition-common",
    "ignition-perspective-common",
]
perspectiveDesigner = [
    "ignition-gson",
    "ignition-common",
    "ignition-designer-api",
    "ignition-perspective-common",
    "ignition-perspective-designer",
]
perspectiveGateway = [
    "ignition-gson",
    "ignition-common",
    "ignition-driver-api",
    "ignition-gateway-api",
    "ignition-perspective-common",
    "ignition-perspective-gateway",
]
kotest = [
    "kotest-assertions-core",
    "kotest-data",
    "kotest-junit",
    "kotest-property",
]
