name: Configure Build Environment
description: Configure Embr's Build Environment (Java + Gradle, Node.js + Yarn)
inputs:
  java-version:
    description: 'Java Version'
    required: true
  node-version:
    description: 'Node.js Version'
    required: true
  gradle-signing-props:
    description: 'Gradle.properties for signing'
    required: true
  module-signing-certificate:
    description: 'Module signing certificate file encoded as a Base64 string'
    required: true
  module-signing-keystore:
    description: 'Module signing keystore file encoded as a Base64 string'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Set up Java ${{ inputs.java-version }}'
      uses: actions/setup-java@v4
      with:
        java-version: '${{ inputs.java-version }}'
        distribution: 'zulu'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: ${{ github.event_name == 'pull_request' }}
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"

    - name: Make gradlew executable
      shell: bash
      run: chmod +x ./gradlew

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '${{ inputs.node-version }}'
        cache: 'yarn'

    - name: Install Dependencies
      shell: bash
      run: yarn install

    - name: Load Organization gradle.properties
      shell: bash
      env:
        props: ${{ inputs.gradle-signing-props }}
      run: |
        mkdir -p ~/.gradle/
        echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
        echo "${props}" > ~/.gradle/gradle.properties

    - name: Load Organization Signing Cert
      shell: bash
      run: |
        mkdir ./secrets
        echo -n "$cert_base64" | base64 --decode > ./secrets/cert.p7b
      env:
        cert_base64: ${{ inputs.module-signing-certificate }}

    - name: Load Organization Keystore
      shell: bash
      run: |
        echo -n "$keystore_base64" | base64 --decode > ./secrets/keystore.jks
      env:
        keystore_base64: ${{ inputs.module-signing-keystore }}