package com.mussonindustrial.embr.gateway.api

fun getMimeTypeFromExtension(extension: String): String? {
    val normalizedExt = extension.lowercase().removePrefix(".")
    return mimeTypes[normalizedExt]
}

val mimeTypes =
    mapOf(
        "aac" to "audio/aac",
        "abw" to "application/x-abiword",
        "apng" to "image/apng",
        "arc" to "application/x-freearc",
        "avif" to "image/avif",
        "avi" to "video/x-msvideo",
        "azw" to "application/vnd.amazon.ebook",
        "bin" to "application/octet-stream",
        "bmp" to "image/bmp",
        "bz" to "application/x-bzip",
        "bz2" to "application/x-bzip2",
        "cda" to "application/x-cdf",
        "csh" to "application/x-csh",
        "cjs" to "text/javascript",
        "css" to "text/css",
        "csv" to "text/csv",
        "doc" to "application/msword",
        "docx" to "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "eot" to "application/vnd.ms-fontobject",
        "epub" to "application/epub+zip",
        "gz" to "application/gzip",
        "gif" to "image/gif",
        "htm" to "text/html",
        "html" to "text/html",
        "ico" to "image/vnd.microsoft.icon",
        "ics" to "text/calendar",
        "jar" to "application/java-archive",
        "jpeg" to "image/jpeg",
        "jpg" to "image/jpeg",
        "js" to "text/javascript",
        "json" to "application/json",
        "jsonld" to "application/ld+json",
        "mid" to "audio/midi",
        "midi" to "audio/midi",
        "mjs" to "text/javascript",
        "mp3" to "audio/mpeg",
        "mp4" to "video/mp4",
        "mpeg" to "video/mpeg",
        "mpkg" to "application/vnd.apple.installer+xml",
        "odp" to "application/vnd.oasis.opendocument.presentation",
        "ods" to "application/vnd.oasis.opendocument.spreadsheet",
        "odt" to "application/vnd.oasis.opendocument.text",
        "oga" to "audio/ogg",
        "ogv" to "video/ogg",
        "ogx" to "application/ogg",
        "opus" to "audio/ogg",
        "otf" to "font/otf",
        "png" to "image/png",
        "pdf" to "application/pdf",
        "php" to "application/x-httpd-php",
        "ppt" to "application/vnd.ms-powerpoint",
        "pptx" to "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "rar" to "application/vnd.rar",
        "rtf" to "application/rtf",
        "sh" to "application/x-sh",
        "svg" to "image/svg+xml",
        "tar" to "application/x-tar",
        "tif" to "image/tiff",
        "tiff" to "image/tiff",
        "ts" to "video/mp2t",
        "ttf" to "font/ttf",
        "txt" to "text/plain",
        "vsd" to "application/vnd.visio",
        "wav" to "audio/wav",
        "weba" to "audio/webm",
        "webm" to "video/webm",
        "webp" to "image/webp",
        "woff" to "font/woff",
        "woff2" to "font/woff2",
        "xhtml" to "application/xhtml+xml",
        "xls" to "application/vnd.ms-excel",
        "xlsx" to "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "xml" to "application/xml",
        "xul" to "application/vnd.mozilla.xul+xml",
        "zip" to "application/zip",
        "3gp" to "video/3gpp",
        "3g2" to "video/3gpp2",
        "7z" to "application/x-7z-compressed",
    )
