# GitHub Actions workflow to automatically build and test Embr.
name: 'build-modules'

on: ['workflow_call', 'workflow_dispatch']

env:
  JAVA_VERSION: 21
  NODE_VERSION: 20

jobs:
  build:
    name: 'Build All Modules'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Fetch git tags' # Required for axion-release-plugin
        run: git fetch --tags --unshallow
      - name: 'Set up Java ${{ env.JAVA_VERSION }}'
        uses: actions/setup-java@v4
        with:
          java-version: '${{ env.JAVA_VERSION }}'
          distribution: 'zulu'
      - name: 'Set up Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '${{ env.NODE_VERSION }}'
      - name: 'Initialize Node.js'
        working-directory: ./js
        run: npm ci
      - name: 'Make gradlew executable'
        run: chmod +x ./gradlew

      - name: 'Restore gradle.properties'
        env:
          GRADLE_IGNITION_MODULE_SIGNING_PROPS: ${{ secrets.GRADLE_IGNITION_MODULE_SIGNING_PROPS }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "${GRADLE_IGNITION_MODULE_SIGNING_PROPS}" > ~/.gradle/gradle.properties
      - name: 'Make secrets folder'
        run: |
          mkdir ./secrets
        shell: bash
      - name: 'Write certificate to file'
        run: |
          echo -n "$IGNITION_MODULE_CERT_BASE64" | base64 --decode > ./secrets/cert.p7b
        env:
          IGNITION_MODULE_CERT_BASE64: ${{ secrets.IGNITION_MODULE_CERT_BASE64 }}
      - name: 'Write keystore to file'
        run: |
          echo -n "$IGNITION_MODULE_KEYSTORE_BASE64" | base64 --decode > ./secrets/keystore.jks
        env:
          IGNITION_MODULE_KEYSTORE_BASE64: ${{ secrets.IGNITION_MODULE_KEYSTORE_BASE64 }}

      - name: 'Build All'
        run: ./gradlew --scan build
      - name: 'Archive build artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: modules
          path: |
            **/*.modl

