name: 'publish-module-chartjs'
on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-modules.yml

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'Download artifacts'
        uses: actions/download-artifact@v4
        with:
          name: modules
  
      - name: 'Release'
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: modules/**.modl
