name: 'publish-modules'
on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-modules.yml
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: 'Download artifacts'
        uses: actions/download-artifact@v4
        with:
          name: modules
          path: artifacts
  
      - name: 'Release'
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: artifacts/**.modl
