name: 'Update Tags'
on:
  workflow_dispatch:
  pull_request:

jobs:
  files-changed:
    name: 'Find Changed Files'
    runs-on: ubuntu-latest
    outputs:
      embr-charts: ${{ steps.changes.outputs.embr-charts }}
      example-perspective-component: ${{ steps.changes.outputs.example-perspective-component }}
    steps:
      - uses: actions/checkout@v4

      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml

  update-tag:
    name: 'Update Tag'
    needs: files-changed
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - embr-charts
          - example-perspective-component
    steps:  
      - name: Bump version and push tag
        if: ${{ needs.files-changed.outputs[matrix.module] == 'true' }} 
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ${{ matrix.module }}-
          release_branches: main
          pre_release_branches: '^(?!main$)'
